# frozen_string_literal: true

require 'structurizr/structurizr_documentation_template'
require 'structurizr/arc42_documentation_template'
require 'structurizr/automatic_documentation_template'
require 'structurizr/viewpoints_and_perspectives_documentation_template'
